fastlane_version "2.56.0"


before_all do |lane, options|
    # Directories
    FASTLANE_DIR  = File.expand_path(File.dirname(File.dirname(__FILE__)))
    IOS_DIR = File.expand_path('../ios')
    ANDROID_DIR = File.expand_path('../android')

    # Build
    IOS_PROJECT         = 'ios/PropertyFinderTS.xcodeproj'
    SCHEME              = ENV["SCHEME"] || 'PropertyFinderTS'
    SIMULATOR_NAME      = ENV["SIMULATOR_NAME"] || "iPhone 6s"
    SIMULATOR_VERSION   = ENV["SIMULATOR_VERSION"] || "9.1"
    CONFIG              = ENV["CONFIG"] || "Debug"

    #HockeyApp Token
    HOCKEY_ANDROID_TOKEN = ENV['HOCKEY_ANDROID_TOKEN']
    HOCKEY_IOS_TOKEN     = ENV['HOCKEY_IOS_TOKEN']
end

platform :android do
  lane :beta do
    # build the release variant
    gradle(project_dir: ANDROID_DIR, task: "assembleRelease")

    # upload to HockeyApp
    hockey(
      api_token: HOCKEY_ANDROID_TOKEN
    )
  end
end

platform :ios do
  lane :beta do
    # build your iOS app
    gym(
      project: IOS_PROJECT,
      scheme: SCHEME,
      export_method: "ad-hoc"
    )

    # upload to HockeyApp
    hockey(
      api_token: HOCKEY_IOS_TOKEN
    )
  end
end

after_all do |lane, options|
    # Directories
    FASTLANE_DIR  = File.expand_path(File.dirname(File.dirname(__FILE__)))
    IOS_DIR = File.expand_path('../ios')
    ANDROID_DIR = File.expand_path('../android')
end