# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "cd544d83-0e93-4a3a-b71f-f61f833eaf86"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to HockeyApp
  hockey(
    # api_token: "YOUR_API_TOKEN"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
