# More documentation about how to customize your build can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "cd544d83-0e93-4a3a-b71f-f61f833eaf86"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :register_devices_dev do
    register_devices(
        devices: {
          "Panpan iphone 7" => "b0abac9398f507ba596e71688fd97ae8e772c1dd"
        }
      )
  end

lane :beta do
  # build your iOS app
  gym(
    scheme: "PropertyFinderTS",
    export_method: "ad-hoc"
  )

  # upload to HockeyApp
  hockey(
    api_token: "6bc866308b9e4e348b01b7fcef98e11c"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
